/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Aplica;

import Clases.Libro;
import java.awt.Dimension;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexandeer
 */
public class frmRgistro extends javax.swing.JFrame {

    Libro objLibro;
    DefaultListModel moLibro, moEditorial, moClase, moAño, moPaginas, moCosto;
    DefaultListModel moEstadisticas;

    public frmRgistro() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultLookAndFeelDecorated(true);
        setResizable(false);
        cargaModelos();
    }

    void cargaModelos() {
        moLibro = new DefaultListModel();
        moEditorial = new DefaultListModel();
        moClase = new DefaultListModel();
        moAño = new DefaultListModel();
        moPaginas = new DefaultListModel();
        moCosto = new DefaultListModel();

        moEstadisticas = new DefaultListModel();

        lstLibro.setModel(moLibro);
        lstEditorial.setModel(moEditorial);
        lstClase.setModel(moClase);
        lstAño.setModel(moAño);
        lstPaginas.setModel(moPaginas);
        lstCosto.setModel(moCosto);

        lstEstadisticas.setModel(moEstadisticas);
    }

    void llenaModelos() {
        moLibro.addElement(objLibro.getNombre());
        moEditorial.addElement(objLibro.getEditorial());
        moClase.addElement(objLibro.getClase());
        moAño.addElement(objLibro.getAño());
        moPaginas.addElement(objLibro.getPaginas());
        moCosto.addElement(objLibro.getCosto());
    }

    void llenaEditorial() {
        comboEditorial.addItem("A");
        comboEditorial.addItem("B");
        comboEditorial.addItem("C");
    }

    void llenaClase() {
        comboClase.addItem("Programacion");
        comboClase.addItem("Analisis");
        comboClase.addItem("Diseño");
    }

    String getLibro() {
        return txtLibro.getText();
    }

    String getEditorial() {
        return String.valueOf(comboEditorial.getSelectedItem());
    }

    String getClase() {
        return String.valueOf(comboClase.getSelectedItem());
    }

    int getAño() {
        return Integer.parseInt(txtAño.getText());
    }

    int getPaginas() {
        return Integer.parseInt(txtPaginas.getText());
    }

    double getCosto() {
        return Double.parseDouble(txtCosto.getText());
    }

    void limpiarCampos() {
        txtAño.setText("");
        txtCosto.setText("");
        txtLibro.setText("");
        txtPaginas.setText("");
        comboClase.setSelectedIndex(0);
        comboEditorial.setSelectedIndex(0);
        txtLibro.requestFocus();
    }

    void LimpiarListas() {
        moAño.clear();
        moClase.clear();
        moCosto.clear();
        moEditorial.clear();
        moEstadisticas.clear();
        moLibro.clear();
        moPaginas.clear();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtLibro = new javax.swing.JTextField();
        txtAño = new javax.swing.JTextField();
        txtPaginas = new javax.swing.JTextField();
        txtCosto = new javax.swing.JTextField();
        comboEditorial = new javax.swing.JComboBox<>();
        comboClase = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstLibro = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEditorial = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstClase = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstAño = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPaginas = new javax.swing.JList<>();
        jScrollPane6 = new javax.swing.JScrollPane();
        lstCosto = new javax.swing.JList<>();
        btnEstadisticas = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        lstEstadisticas = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRO DE LIBROS");

        panelPrincipal.setForeground(new java.awt.Color(0, 0, 102));
        panelPrincipal.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
        jLabel2.setText("REGISTRO DEL LIBRO");
        panelPrincipal.add(jLabel2);
        jLabel2.setBounds(260, 0, 290, 40);

        txtLibro.setForeground(new java.awt.Color(0, 0, 102));
        txtLibro.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre del Libro", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(txtLibro);
        txtLibro.setBounds(10, 40, 400, 60);

        txtAño.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        txtAño.setForeground(new java.awt.Color(0, 0, 102));
        txtAño.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtAño.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Año de Edición", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(txtAño);
        txtAño.setBounds(10, 100, 110, 60);

        txtPaginas.setForeground(new java.awt.Color(0, 0, 102));
        txtPaginas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Páginas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(txtPaginas);
        txtPaginas.setBounds(120, 100, 100, 60);

        txtCosto.setForeground(new java.awt.Color(0, 0, 102));
        txtCosto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Costo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(txtCosto);
        txtCosto.setBounds(220, 100, 110, 60);

        comboEditorial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "A", "B", "C" }));
        comboEditorial.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Editorial", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(comboEditorial);
        comboEditorial.setBounds(420, 40, 150, 60);

        comboClase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Programación", "Análisis", "Diseño" }));
        comboClase.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Clase", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        panelPrincipal.add(comboClase);
        comboClase.setBounds(580, 40, 150, 60);

        btnRegistrar.setText("REGISTRAR");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnRegistrar);
        btnRegistrar.setBounds(350, 110, 130, 50);

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnLimpiar);
        btnLimpiar.setBounds(480, 110, 120, 50);

        jScrollPane1.setViewportView(lstLibro);

        panelPrincipal.add(jScrollPane1);
        jScrollPane1.setBounds(10, 170, 330, 220);

        jScrollPane2.setViewportView(lstEditorial);

        panelPrincipal.add(jScrollPane2);
        jScrollPane2.setBounds(340, 170, 50, 220);

        jScrollPane3.setViewportView(lstClase);

        panelPrincipal.add(jScrollPane3);
        jScrollPane3.setBounds(390, 170, 100, 220);

        jScrollPane4.setViewportView(lstAño);

        panelPrincipal.add(jScrollPane4);
        jScrollPane4.setBounds(490, 170, 70, 220);

        jScrollPane5.setViewportView(lstPaginas);

        panelPrincipal.add(jScrollPane5);
        jScrollPane5.setBounds(560, 170, 80, 220);

        jScrollPane6.setViewportView(lstCosto);

        panelPrincipal.add(jScrollPane6);
        jScrollPane6.setBounds(640, 170, 80, 220);

        btnEstadisticas.setBackground(new java.awt.Color(0, 0, 0));
        btnEstadisticas.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        btnEstadisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnEstadisticas.setText("ESTADÍSTICAS");
        btnEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstadisticasActionPerformed(evt);
            }
        });
        panelPrincipal.add(btnEstadisticas);
        btnEstadisticas.setBounds(10, 400, 720, 32);

        jScrollPane8.setViewportView(lstEstadisticas);

        panelPrincipal.add(jScrollPane8);
        jScrollPane8.setBounds(10, 440, 720, 150);

        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelPrincipal.add(jButton1);
        jButton1.setBounds(600, 110, 120, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (txtLibro.getText().isEmpty() || txtAño.getText().isEmpty() || txtCosto.getText().isEmpty() || txtPaginas.getText().isEmpty() || comboClase.getSelectedIndex() == 0 || comboEditorial.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(null, "Debe rellenar todos los campos");
        } else {
            try {
                objLibro = new Libro(getLibro(), getEditorial(), getClase(),
                        getAño(), getPaginas(), getCosto());
                llenaModelos();
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null,
                        "Error en la Aplicacion " + ex.getMessage());
            }
            limpiarCampos();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstadisticasActionPerformed
        try {
            moEstadisticas.clear();
            moEstadisticas.addElement("Numero de Libro de Análisis de la Editorial B es: " + objLibro.getTAnalisis());
            int mayor = Integer.MIN_VALUE;
            int pos = 0;
            for (int i = 0; i < moLibro.getSize(); i++) {
                if (Integer.parseInt(moAño.elementAt(i).toString()) > mayor) {
                    mayor = Integer.parseInt(moAño.elementAt(i).toString());
                    pos = i;
                }
            }

            moEstadisticas.addElement("Libro con el año de edición más reciente: " + moLibro.getElementAt(pos));

            int menor = Integer.MAX_VALUE;
            for (int i = 0; i < moLibro.getSize(); i++) {
                if (Integer.parseInt(moPaginas.elementAt(i).
                        toString()) < menor) {
                    menor = Integer.parseInt(moPaginas.elementAt(i).toString());
                    pos = i;
                }
            }

            moEstadisticas.addElement("Editorial con libro de menor pagina es : " + moEditorial.getElementAt(pos));

            double mayorCosto = Double.MIN_VALUE;
            for (int i = 0; i < moLibro.getSize(); i++) {
                if (Double.parseDouble(moCosto.elementAt(i)
                        .toString()) > mayorCosto) {
                    mayorCosto = Double.parseDouble(moCosto.elementAt(i)
                            .toString());
                    pos = i;
                }
            }
            moEstadisticas.addElement("Libro con mayor costo es:  " + moLibro.getElementAt(pos));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error en la Aplicacion " + ex.getMessage());
        }
    }//GEN-LAST:event_btnEstadisticasActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtAño.setText("");
        txtCosto.setText("");
        txtLibro.setText("");
        txtPaginas.setText("");
        comboClase.setSelectedIndex(0);
        comboEditorial.setSelectedIndex(0);
        txtLibro.requestFocus();
        LimpiarListas();


    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int r = JOptionPane.showOptionDialog(this,
                "¿Estas seguro de Salir?", "Salida", JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, new Object[]{"SI", "NO"}, "NO");
        if (r == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmRgistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmRgistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmRgistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmRgistro.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmRgistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEstadisticas;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> comboClase;
    private javax.swing.JComboBox<String> comboEditorial;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JList<String> lstAño;
    private javax.swing.JList<String> lstClase;
    private javax.swing.JList<String> lstCosto;
    private javax.swing.JList<String> lstEditorial;
    private javax.swing.JList<String> lstEstadisticas;
    private javax.swing.JList<String> lstLibro;
    private javax.swing.JList<String> lstPaginas;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTextField txtAño;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtLibro;
    private javax.swing.JTextField txtPaginas;
    // End of variables declaration//GEN-END:variables
}
